### PR TITLE
Refactor field: vdims

### PR DESCRIPTION
**Pull request by lang-m**
- renamed: `dim` -> `nvdim`
- renamed: `components` -> `vdims`
- removed: `coordinate_field`
- removed: typesystem decorator

Todo
 
- [x] check doctests
- [x] update docstrings

### CODE REVIEW

**Comment by lang-m** [comment]
We have to think about how to change the docstrings (e.g. when talking about "field components").

**Comment by samjrholt** [comment]
@lang-m looks good, just take a look at the field rotator as discussed. I will take a look through the documentation and let you know when I'm done.

**Comment by lang-m** [comment]
@samjrholt I have fixed the FieldRotator and tools where failures are related to `nvdim` or `vdims`.

**Comment by lang-m** [comment]
@samjrholt You can merge the PR when you are done.

**Pull request merged**
