### PR TITLE
WIP: activate colour in pytest output in github actions

### PR DESCRIPTION
**Pull request by fangohr**
First test to see if this works (activate colour in pytest output in github actions).

### CODE REVIEW

**Comment by lang-m** [comment]
@fangohr I have updated the workflow file on `master`. Could you please try again.

**Comment by lang-m** [comment]
On other pull requests they are now running twice (pull_request and push).

**Comment by fangohr** [comment]
> On other pull requests they are now running twice (pull_request and push).

Hm, yes - I have seen that in many projects. One would think there is a simple solution to this (but I haven't investigated at all yet).

**Comment by lang-m** [comment]
@fangohr Commit [8bf67c3](https://github.com/ubermag/discretisedfield/commit/8bf67c36fc9f1ec2e2f09215274393862968ce69) changes the `on: push` action trigger to run only on master branch. That avoids the problem of duplicated test runs. Small downside: commits on other branches are tested only after a PR is opened. I think that is no big problem for us. Additionally, I've added `workflow_dispatch` to manually run a test on a different branch.

**Comment by lang-m** [comment]
I like the changes introduced in this PR but I would suggest that we do it for all repos together using the scripts in `devtools` and change directly on `master`. I can do that when you say that this is ready @fangohr (and show you if you are interested).

**Comment by fangohr** [comment]
> I like the changes introduced in this PR but I would suggest that we do it for all repos together using the scripts in `devtools` and change directly on `master`. I can do that when you say that this is ready @fangohr (and show you if you are interested).

Yes - that was my plan: test for one package, and once this is working roll out systematically. I'd like to see it :)

**Comment by lang-m** [comment]
This has been added via [6dc009c](https://github.com/ubermag/discretisedfield/commit/6dc009c97f424b09b2662f2d1cca724a48a2ec37).

**Pull request closed without merging**
